### ISSUE TITLE
Laufenden Timer anzeigen

### ISSUE THREAD

**Issue by DevFreeze** [sarah-jessica/Uhr#2]
Ausgangslage: Wenn man auf den Timer-Tab klickt wird immer der TimerScreen angezeigt, auch wenn schon ein Timer läuft.

Ziel: Wenn bereits ein Timer läuft soll der laufende Timer angezeigt werden, ansonsten soll ein Timer eingestellt werden können.

Aufgaben:

- [x] Den StopWatchTimer aus dem RunningTimerScreen in die timer/data_provider.dart verschieben, damit global verfügbar.
- [x] Den RunningTimerScreen und TimerScreen in Widgets umwandeln (also eigentlich nur das Scaffold entfernen, umbenennen und verschieben).
- [x] Einen neuen TimerScreen anlegen. In diesem TimerScreen wird der Status des StopWatchTimer aus der timer/data_provider.dart abgerufen (isRunning). Wenn ein Timer bereits läuft -> zeig das RunningTimerWidget, wenn nicht dann das TimerWidget

**Comment by sarah-jessica** [comment]
Ist in einem neuen Branch gelöst. Im Pull request hab ich noch was dazu geschrieben :)
