### ISSUE TITLE
NotificationService Verbesserungen

### ISSUE THREAD

**Issue by DevFreeze** [sarah-jessica/Uhr#4]
Ausgangslage: NotificationService funktioniert, aber der Code könnte noch an einigen Stellen verbessert werden, um übersichtlicher und weniger fehleranfällig zu werden.

__Prinzip: DRY (Don't repeat yourself)__

Die NotificationDetails werden an drei verschiedenen Stellen genau gleich übergeben.
Besser: Eine Variable am Anfang der Klasse definieren, die dann immer wieder verwendet wird:

```
final notificationDetails = const NotificationDetails(
    android: AndroidNotificationDetails(
      'main_channel',
      'Main Channel',
      importance: Importance.max,
      priority: Priority.max,
      icon: '@mipmap/ic_launcher',
      playSound: true,
      //sound: RawResourceAndroidNotificationSound('alarm_buzzer_experia'),
      enableVibration: true,
    ),
  );
```

Innerhalb der Funktion `showNotification` wird `flutterLocalNotificationsPlugin.zonedSchedule(...)` ebenfalls zweimal aufgerufen mit fast gleichen ÜbergabeParametern.

Besser: Anstelle der übergeordneten If-Bedingung einen ternären Operator nutzen. In Verbindung mit der vorher definierten Variable für die NotificationDetails kann die Funktion auf folgenden Code reduziert werden:

```
Future<void> showNotification(int id, String title, String body, DateTime time, bool rep) async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
      id,
      title,
      body,
      tz.TZDateTime.from(time, tz.getLocation('Europe/Berlin')),
      notificationDetails,
      uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
      androidAllowWhileIdle: true,
      matchDateTimeComponents: rep == false ? null : DateTimeComponents.time,
    );
  }
```

---------------------------------------------------

__Prinzip: Don't add obvious noise__

Mit Dart müssen Variablen nicht zwingen typisiert werden. Zum Beispiel kann:

`final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();`

ebenfalls folgendermaßen definiert werden:

`final flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();`

Es gehen dabei keine Informationen verloren, da immer noch klar ist, dass es sich bei der Variable um ein _FlutterLocalNotificationsPlugin_ handelt, aber es wird weniger Code verwendet, was die Übersichtlichkeit und Lesbarkeit verbessert.

**Comment by sarah-jessica** [comment]
Hab ich im _show_running_timer_if_running_ Branch gleich mal implementiert
